games:
- name: Age of Empires II
  type: game
  installer_type: msi
  base_path: Installers/Age of Empires II/game
  install_msi: Age of Empires II.msi
  supports_player_name: true
  prerequisites: []
- name: Battlefield 1942
  type: game
  installer_type: msi
  base_path: Installers/Battlefield 1942/game
  install_msi: Battlefield 1942.msi
  supports_player_name: true
  prerequisites: []
- name: Battlefield 3
  type: game
  installer_type: inno_setup
  base_path: Installers/Battlefield 3/Game
  install_exe: Battlefield 3.exe
  supports_player_name: true
  prerequisites: []
- name: Battlefield 4
  type: game
  installer_type: inno_setup
  base_path: Installers/Battlefield 4/Game
  install_exe: Battlefield 4.exe
  supports_player_name: true
  prerequisites: []
- name: Battlefield Bad Company 2
  type: game
  installer_type: msi
  base_path: Installers/Battlefield Bad Company 2/Game
  install_msi: Battlefield Bad Company 2.msi
  supports_player_name: true
  requires_server_ip: true
  prerequisites: []
- name: Battlefield Bad Company 2 Server
  type: server
  installer_type: msi
  base_path: Installers/Battlefield Bad Company 2/Server
  install_msi: Battlefield Bad Company 2 Server.msi
  supports_player_name: true
  prerequisites: []
- name: BF-Portable
  type: server
  installer_type: inno_setup
  base_path: Installers/BF-Portable/server
  install_exe: BF-Portable.exe
  supports_player_name: true
  prerequisites: []
- name: Call Of Duty
  type: game
  installer_type: msi
  base_path: Installers/Call Of Duty/Game
  install_msi: Call Of Duty.msi
  supports_player_name: true
  prerequisites: []
- name: Call Of Duty 4
  type: game
  installer_type: msi
  base_path: Installers/Call Of Duty 4/Game
  install_msi: Call Of Duty 4.msi
  supports_player_name: true
  prerequisites: []
- name: Chivalry Medieval Warfare
  type: game
  installer_type: msi
  base_path: Installers/Chivalry Medieval Warfare/Game
  install_msi: Chivalry Medieval Warfare.msi
  supports_player_name: true
  prerequisites: []
- name: Chivalry Medieval Warfare Server
  type: server
  installer_type: msi
  base_path: Installers/Chivalry Medieval Warfare/Server
  install_msi: Chivalry Medieval Warfare Server.msi
  supports_player_name: true
  prerequisites: []
- name: Counter Strike 2
  type: game
  installer_type: inno_setup
  base_path: Installers/Counter Strike 2/game
  install_exe: Counter Strike 2.exe
  supports_player_name: true
  prerequisites: []
- name: Counter-Strike Global Offensive
  type: game
  installer_type: msi
  base_path: Installers/Counter-Strike Global Offensive/Game
  install_msi: Counter-Strike Global Offensive.msi
  supports_player_name: true
  prerequisites: []
- name: Duck Game
  type: game
  installer_type: msi
  base_path: Installers/Duck Game/game
  install_msi: Duck Game.msi
  supports_player_name: true
  prerequisites: []
- name: Flatout 2
  type: game
  installer_type: msi
  base_path: Installers/Flatout 2/Game
  install_msi: Flatout 2.msi
  supports_player_name: true
  prerequisites: []
- name: Garrys Mod
  type: game
  installer_type: msi
  base_path: Installers/Garrys Mod/Game
  install_msi: Garrys Mod.msi
  supports_player_name: true
  prerequisites: []
- name: Grand Theft Auto IV
  type: game
  installer_type: msi
  base_path: Installers/Grand Theft Auto IV/game
  install_msi: Grand Theft Auto IV.msi
  supports_player_name: true
  prerequisites: []
- name: Killing Floor
  type: game
  installer_type: msi
  base_path: Installers/Killing Floor/Game
  install_msi: Killing Floor.msi
  supports_player_name: true
  prerequisites: []
- name: Left 4 Dead 2
  type: game
  installer_type: msi
  base_path: Installers/Left 4 Dead 2/Game
  install_msi: Left 4 Dead 2.msi
  supports_player_name: true
  prerequisites: []
- name: Need for Speed SHIFT
  type: game
  installer_type: msi
  base_path: Installers/Need for Speed SHIFT/Game
  install_msi: Need for Speed SHIFT.msi
  supports_player_name: true
  prerequisites: []
- name: Red Alert 3
  type: game
  installer_type: msi
  base_path: Installers/Red Alert 3/Game
  install_msi: Red Alert 3.msi
  supports_player_name: true
  prerequisites: []
- name: StarCraft II
  type: game
  installer_type: msi
  base_path: Installers/StarCraft II/game
  install_msi: StarCraft II.msi
  supports_player_name: true
  prerequisites: []
- name: Team Fortress 2
  type: game
  installer_type: msi
  base_path: Installers/Team Fortress 2/Game
  install_msi: Team Fortress 2.msi
  supports_player_name: true
  prerequisites: []
- name: Tom Clancys Rainbow Six Siege
  type: game
  installer_type: msi
  base_path: Installers/Tom Clancys Rainbow Six Siege/game
  install_msi: Tom Clancys Rainbow Six Siege.msi
  supports_player_name: true
  prerequisites: []
- name: Unreal Tournament 3
  type: game
  installer_type: msi
  base_path: Installers/Unreal Tournament 3/Game
  install_msi: Unreal Tournament 3.msi
  supports_player_name: true
  prerequisites: []
- name: Warcraft III
  type: game
  installer_type: msi
  base_path: Installers/Warcraft III/Game
  install_msi: Warcraft III.msi
  supports_player_name: true
  prerequisites: []
- name: Wreckfest
  type: game
  installer_type: inno_setup
  base_path: Installers/Wreckfest/game
  install_exe: Wreckfest.exe
  supports_player_name: true
  prerequisites: []
