games:
- name: Age of Empires II
  type: game
  installer_type: msi
  base_path: Installers/Age of Empires II/game
  version: '1.0'
  install_msi: Age of Empires II.msi
  supports_player_name: false
  prerequisites: []
- name: Duck Game
  type: game
  installer_type: msi
  base_path: Installers/Duck Game/game
  version: 1.00.0000
  install_msi: Duck Game.msi
  supports_player_name: false
  prerequisites: []
