games:
- name: Battlefield 3
  type: game
  installer_type: inno_setup
  base_path: Installers/Battlefield 3/Game
  version: '1.0'
  install_exe: Battlefield 3.exe
  supports_player_name: false
  prerequisites: []
- name: Battlefield 4
  type: game
  installer_type: inno_setup
  base_path: Installers/Battlefield 4/Game
  version: '1.0'
  install_exe: Battlefield 4.exe
  supports_player_name: false
  prerequisites: []
- name: Counter Strike 2
  type: game
  installer_type: inno_setup
  base_path: Installers/Counter Strike 2/game
  version: '1.0'
  install_exe: Counter Strike 2.exe
  supports_player_name: true
  prerequisites: []
- name: Wreckfest
  type: game
  installer_type: inno_setup
  base_path: Installers/Wreckfest/game
  version: '1.0'
  install_exe: Wreckfest.exe
  supports_player_name: true
  prerequisites: []
