games:
  Age of Empires II:
    files:
    - path: Age of Empires II.msi
      crc32: BC78D1AA
  Duck Game:
    files:
    - path: Data1.cab
      crc32: 6150592A
    - path: Duck Game.msi
      crc32: 2E6BA5B8
    - path: setup.exe
      crc32: 58443D9E
