games:
  Battlefield 3:
    files:
    - path: Battlefield 3-1.bin
      crc32: 1A1F68A1
    - path: Battlefield 3-10.bin
      crc32: 1BE9A919
    - path: Battlefield 3-11.bin
      crc32: D81899F2
    - path: Battlefield 3-12.bin
      crc32: CC45E2D3
    - path: Battlefield 3-13.bin
      crc32: 4140877B
    - path: Battlefield 3-14.bin
      crc32: C81EFDE7
    - path: Battlefield 3-15.bin
      crc32: 39934B1E
    - path: Battlefield 3-16.bin
      crc32: 0BA5B8CB
    - path: Battlefield 3-17.bin
      crc32: C1EA0F78
    - path: Battlefield 3-18.bin
      crc32: 9DDA1DCF
    - path: Battlefield 3-19.bin
      crc32: 96D47C6E
    - path: Battlefield 3-2.bin
      crc32: 1C323DD9
    - path: Battlefield 3-3.bin
      crc32: C2B6E528
    - path: Battlefield 3-4.bin
      crc32: 357856E4
    - path: Battlefield 3-5.bin
      crc32: 5902B5ED
    - path: Battlefield 3-6.bin
      crc32: 145862BD
    - path: Battlefield 3-7.bin
      crc32: FCB485D8
    - path: Battlefield 3-8.bin
      crc32: BA1168A9
    - path: Battlefield 3-9.bin
      crc32: B27FAA4C
    - path: Battlefield 3.exe
      crc32: 9420B04A
  Battlefield 4:
    files:
    - path: Battlefield 4-1.bin
      crc32: E6C4C192
    - path: Battlefield 4-10.bin
      crc32: D7785306
    - path: Battlefield 4-11.bin
      crc32: 3AFD5DD4
    - path: Battlefield 4-12.bin
      crc32: A72E501B
    - path: Battlefield 4-13.bin
      crc32: D551B940
    - path: Battlefield 4-14.bin
      crc32: '67284816'
    - path: Battlefield 4-15.bin
      crc32: 1399D98F
    - path: Battlefield 4-16.bin
      crc32: BF159125
    - path: Battlefield 4-17.bin
      crc32: 206C3911
    - path: Battlefield 4-18.bin
      crc32: B5D3E844
    - path: Battlefield 4-19.bin
      crc32: 91A3E9D6
    - path: Battlefield 4-2.bin
      crc32: 6BC4A8EB
    - path: Battlefield 4-20.bin
      crc32: B792FDAC
    - path: Battlefield 4-21.bin
      crc32: EB0AC3F6
    - path: Battlefield 4-22.bin
      crc32: 93A864EB
    - path: Battlefield 4-23.bin
      crc32: 106CA459
    - path: Battlefield 4-24.bin
      crc32: 62B7890F
    - path: Battlefield 4-25.bin
      crc32: 2EAED69E
    - path: Battlefield 4-26.bin
      crc32: 660AC625
    - path: Battlefield 4-27.bin
      crc32: BDE651C7
    - path: Battlefield 4-28.bin
      crc32: 130379E4
    - path: Battlefield 4-29.bin
      crc32: 7463EBAB
    - path: Battlefield 4-3.bin
      crc32: 504D9820
    - path: Battlefield 4-30.bin
      crc32: '74135458'
    - path: Battlefield 4-31.bin
      crc32: DD858589
    - path: Battlefield 4-32.bin
      crc32: A8F575D8
    - path: Battlefield 4-33.bin
      crc32: 14178D89
    - path: Battlefield 4-34.bin
      crc32: 7C45473E
    - path: Battlefield 4-35.bin
      crc32: C7151345
    - path: Battlefield 4-36.bin
      crc32: '10835938'
    - path: Battlefield 4-37.bin
      crc32: 09509CBB
    - path: Battlefield 4-4.bin
      crc32: D2E48683
    - path: Battlefield 4-5.bin
      crc32: 4C74AF43
    - path: Battlefield 4-6.bin
      crc32: 2D831452
    - path: Battlefield 4-7.bin
      crc32: EEEE9C0F
    - path: Battlefield 4-8.bin
      crc32: D6041B32
    - path: Battlefield 4-9.bin
      crc32: B81A6AB9
    - path: Battlefield 4.exe
      crc32: 895A434B
  Counter Strike 2:
    files:
    - path: Counter Strike 2-1.bin
      crc32: B510DE12
    - path: Counter Strike 2-10.bin
      crc32: 6CD6677D
    - path: Counter Strike 2-11.bin
      crc32: 683C180E
    - path: Counter Strike 2-12.bin
      crc32: A7B5F5B3
    - path: Counter Strike 2-13.bin
      crc32: CCA68C95
    - path: Counter Strike 2-14.bin
      crc32: 911F26FA
    - path: Counter Strike 2-15.bin
      crc32: BEC4DC81
    - path: Counter Strike 2-16.bin
      crc32: 5FBAD9BD
    - path: Counter Strike 2-17.bin
      crc32: FCAD9BAB
    - path: Counter Strike 2-18.bin
      crc32: 238B7287
    - path: Counter Strike 2-19.bin
      crc32: 5E4812A2
    - path: Counter Strike 2-2.bin
      crc32: 4A4BD6B3
    - path: Counter Strike 2-20.bin
      crc32: 19E6A59D
    - path: Counter Strike 2-21.bin
      crc32: FF09CDB7
    - path: Counter Strike 2-22.bin
      crc32: 02C70302
    - path: Counter Strike 2-23.bin
      crc32: DFF56C9B
    - path: Counter Strike 2-24.bin
      crc32: A1C98DA5
    - path: Counter Strike 2-25.bin
      crc32: EB3C293A
    - path: Counter Strike 2-26.bin
      crc32: 6B1970C0
    - path: Counter Strike 2-27.bin
      crc32: D8C56684
    - path: Counter Strike 2-28.bin
      crc32: CA9DFAD2
    - path: Counter Strike 2-29.bin
      crc32: ACD832A7
    - path: Counter Strike 2-3.bin
      crc32: A3BFA621
    - path: Counter Strike 2-30.bin
      crc32: AAE9173D
    - path: Counter Strike 2-31.bin
      crc32: 384BA6FD
    - path: Counter Strike 2-32.bin
      crc32: DB5FE368
    - path: Counter Strike 2-4.bin
      crc32: 7CCFFA45
    - path: Counter Strike 2-5.bin
      crc32: '25358423'
    - path: Counter Strike 2-6.bin
      crc32: 9E1C6FDC
    - path: Counter Strike 2-7.bin
      crc32: ACC9201B
    - path: Counter Strike 2-8.bin
      crc32: 21232CD6
    - path: Counter Strike 2-9.bin
      crc32: 744140ED
    - path: Counter Strike 2.exe
      crc32: 17F1A486
  Wreckfest:
    files:
    - path: Wreckfest-1.bin
      crc32: EA70B17E
    - path: Wreckfest-10.bin
      crc32: 9E243181
    - path: Wreckfest-11.bin
      crc32: 05DEBA43
    - path: Wreckfest-12.bin
      crc32: 9F22F561
    - path: Wreckfest-13.bin
      crc32: C53D9362
    - path: Wreckfest-14.bin
      crc32: 6369D729
    - path: Wreckfest-15.bin
      crc32: DFCEF14F
    - path: Wreckfest-16.bin
      crc32: E48E95BB
    - path: Wreckfest-17.bin
      crc32: 2423B5C5
    - path: Wreckfest-18.bin
      crc32: 637638A7
    - path: Wreckfest-2.bin
      crc32: BF7369C5
    - path: Wreckfest-3.bin
      crc32: EA5F6390
    - path: Wreckfest-4.bin
      crc32: A4604214
    - path: Wreckfest-5.bin
      crc32: 8F439307
    - path: Wreckfest-6.bin
      crc32: 08F716C0
    - path: Wreckfest-7.bin
      crc32: 177BAABA
    - path: Wreckfest-8.bin
      crc32: B91496C4
    - path: Wreckfest-9.bin
      crc32: B2F6B516
    - path: Wreckfest.exe
      crc32: 7B001927
